# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Sugar-Args
version:      1.3
version_from: lib/POE/Sugar/Args.pm
installdirs:  site
requires:
    Devel::Caller::Perl:           1.4
    Exporter::Lite:                0
    POE:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
